name: card_game
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  http: ^1.1.0
  dartz: ^0.10.1
  flutter_bloc: ^8.1.3
  bloc: ^8.1.2
  bloc_concurrency: ^0.2.3
  get_it: ^7.6.0
  shared_preferences: ^2.2.0
  intl: ^0.18.0
  injectable: ^2.1.2
  fluttertoast: ^8.2.2
  animation_wrappers: ^3.0.0
  auto_route: ^7.8.0
  socket_io_client: ^1.0.1
  socket_io: ^1.0.1
  socket_io_common: ^1.0.1
  connectivity_plus: ^5.0.2
  bitsdojo_window: ^0.1.6
  sembast: ^3.5.0+1
  flutter_svg: ^2.0.9



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  injectable_generator: ^2.1.6
  auto_route_generator:

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/png/
    - assets/images/svg/
    - assets/images/svg/j/
    - assets/images/svg/k/
    - assets/images/svg/q/


  fonts:
    - family: Yekan
      fonts:
        - asset: assets/fonts/iy_black.ttf
          weight: 800
        - asset: assets/fonts/iy_bold.ttf
          weight: 700
        - asset: assets/fonts/iy_medium.ttf
          weight: 600
        - asset: assets/fonts/iy_regular.ttf
          weight: 500
        - asset: assets/fonts/iy_thin.ttf
          weight: 400
        - asset: assets/fonts/iy_light.ttf
          weight: 300
    # - family: Icomoon
    #   fonts:
    #     - asset: assets/fonts/icomoon.ttf
